### ISSUE TITLE
vimba error

### ISSUE THREAD

**Issue by Anna4142** [Anna4142/PrisonerDilemmaPy#60]
Traceback (most recent call last):
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\camera.py", line 232, in wait_for_frames
    call_vimba_c('VmbCaptureFrameWait', self.context.cam_handle, byref(frame_handle),
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\c_binding\vimba_c.py", line 757, in call_vimba_c
    getattr(_lib_instance, func_name)(*args)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\c_binding\vimba_c.py", line 675, in _eval_vmberror
    raise VimbaCError(result)
vimba.c_binding.vimba_common.VimbaCError: VimbaCError(<VmbError.Timeout: -12>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\EngelHardBlab.MEDICINE\Downloads\PrisonerDilemmaPy_(4)\PrisonerDilemmaPy\Experiment_Launcher_code\ExperimentLauncher.py", line 49, in <module>
    main()
  File "C:\Users\EngelHardBlab.MEDICINE\Downloads\PrisonerDilemmaPy_(4)\PrisonerDilemmaPy\Experiment_Launcher_code\ExperimentLauncher.py", line 30, in main
    expManager.start_streaming_exp(experiment_name, num_trials, decision_time, return_time, opponent_type,
  File "C:\Users\EngelHardBlab.MEDICINE\Downloads\PrisonerDilemmaPy_(4)\PrisonerDilemmaPy\Experiment_Launcher_code\ExperimentManager.py", line 311, in start_streaming_exp
    zone_activations = self.videoAnalyser.process_single_frame(self.timestamps)
  File "C:\Users\EngelHardBlab.MEDICINE\Downloads\PrisonerDilemmaPy_(4)\PrisonerDilemmaPy\Video_analyser_code\VideoAnalyser.py", line 242, in process_single_frame
    frame = self.cam.get_frame().as_opencv_image()
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\util\context_decorator.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\util\runtime_type_check.py", line 60, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\camera.py", line 675, in get_frame
    return next(self.get_frame_generator(1, timeout_ms, allocation_mode))
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\camera.py", line 324, in _frame_generator
    fsm.wait_for_frames(timeout_ms)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\camera.py", line 299, in wait_for_frames
    self.__state.wait_for_frames(timeout_ms)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\EngelHardBlab.MEDICINE\anna-anna-2022-06-16\cameratrial\venv\lib\site-packages\vimba\camera.py", line 236, in wait_for_frames
    raise _build_camera_error(self.context.cam, e) from e
vimba.error.VimbaTimeout: Frame capturing on Camera 'DEV_1AB22C012A3B' timed out.

**Comment by MickyHoltzman** [comment]
There are no known issues with the Vimba drivers. Regardless, this is not relevant anynmore, new vimba (XSDK) drivers are being used.
